[package]
  name = "typenum"
  build = "build.rs"
  version = "1.5.2"
  authors = [
    "Paho Lurie-Gregg <paho@paholg.com>",
    "Andre Bogus <bogusandre@gmail.com>"
  ]
  description = "Typenum is a Rust library for type-level numbers evaluated at compile time. It currently supports bits, unsigned integers, and signed integers. It also provides a type-level array of type-level numbers, but its implementation is incomplete."
  homepage = "http://paholg.com/project/typenum"
  documentation = "http://paholg.com/typenum"
  repository = "https://github.com/paholg/typenum"
  readme = "README.md"
  license = "MIT/Apache-2.0"

[lib]
  name = "typenum"

[features]
  no_std = []

[dependencies]
  clippy = { version = "0.0.114", optional = true }
